### ISSUE TITLE
Navbar not closing on mobile devices 

### ISSUE THREAD

**Issue by mutungapeter** [design-sparx/mantine-analytics-dashboard#43]
The navbar once opened in mobile devices , the close icon/burger isn't closing the navbar menu .In addition on clicking the navlinks on mobile devices  ,i think the navbar should close automatically and redirect to the link.
![Screenshot (139)](https://github.com/design-sparx/mantine-analytics-dashboard/assets/81368127/d96e3dff-55a9-408f-9d58-1669b1a6b78e)

**Comment by kelvink96** [comment]
Let me check it out.
